substitutions:
  devicename: ainsleymonitor
  tx_pin: GPIO4
  rx_pin: GPIO5
  led_pin: GPIO14
  button_pin: GPIO13
  sensor_update: 60s

esphome:
  name: $devicename

esp8266:
  board: esp07s #esp01_1m #d1_mini_pro

wifi:
  networks:
    - ssid: !secret wifi_comp_ssid
      password: !secret wifi_comp_password
    - ssid: !secret wifi_home_ssid
      password: !secret wifi_home_password
    - ssid: !secret wifi_phone_ssid
      password: !secret wifi_phone_password
    - ssid: !secret wifi_bshed_ssid
      password: !secret wifi_bshed_password

interval:
  - interval: $sensor_update
    then: #publish wifi info every sensor_update interval as it is not valid when WiFi first starts up
      - mqtt.publish:
          topic: $devicename/sensor/wifi_ssid/state
          payload: !lambda |-
            return id(wifi_ssid).state;
      - mqtt.publish:
          topic: $devicename/sensor/wifi_dns/state
          payload: !lambda |-
            return id(wifi_dns).state;
      - mqtt.publish:
          topic: $devicename/sensor/wifi_ip/state
          payload: !lambda |-
            return id(wifi_ip).state;

mqtt:
  broker: allsmiths.synology.me
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  #no clientid reqd
  discovery: true # disable entity discovery
  discover_ip: true # enable device discovery
  discovery_retain: true #retain discovery messages
  discovery_unique_id_generator: mac #Use Mac address to generate unique entity Ids

ota:
  platform: esphome

logger:
  baud_rate: 0 # disable uart logging (MQTT logging still happens) as we need to retain the serial port free for comms with AT Mega
  level: DEBUG

button: 
  - platform: restart
    id: restart_button
    name: Restart

binary_sensor:
  - platform: gpio
    pin: 
      number: $button_pin
      inverted: True
    name: "ESP8266 Button"

light:
  - platform: status_led
    name: "ESP8266 LED"
    id: devicename_led
    pin: 
      number: $led_pin
      inverted: False

text_sensor:
  - platform: wifi_info
    ssid:
      icon: mdi:wifi
      id: wifi_ssid
      name: "WiFi SSID"
    dns_address:
      icon: mdi:wifi
      id: wifi_dns
      name: "WiFi DNS"
    ip_address:
      icon: mdi:wifi
      id: wifi_ip
      name: "WiFi IP"

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    icon: mdi:wifi
    name: "WiFi Signal dB"
    id: wifi_signal_db
    unit_of_measurement: "dB"
    update_interval: ${sensor_update}
    entity_category: "diagnostic"
                
  - platform: uptime
    name: "Uptime"
