# Specific code for the Home Assistant Boat Monitor main unit goes in here
#

esphome:
  name: ${esphome_name}

external_components:
  - source: github://eigger/espcomponents@latest
    components: [ uartex ]
    refresh: always

uartex:
  rx_timeout: 30ms #was 10ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3
  # rx_priority: loop #Lower priority for Rx than main loop tasks
  rx_header: [0x21, 0x24] #All messages start !$
  rx_footer: [0x0D, 0x0A] #All messages end CRLF
  # tx_header: [0x02, 0x01]
  tx_footer: [0x0D, 0x0A]

  version:
    name: "Uartex Version"
    disabled: False
  error:
    name: "Uartex Error"
    disabled: False
  log:
    name: "Uartex Log"
    disabled: True #False

number:
  - platform: template
    id: soc_warn_level
    name: "SOC warning level"
    max_value: 100
    min_value: 0
    step: 1
    optimistic: true  
    initial_value: 85
    restore_value: true
    on_value: 
      then:
        - script.execute: soc_check_alarm
  - platform: template
    id: soc_alarm_level
    name: "SOC alarm level"
    max_value: 100
    min_value: 0
    step: 1
    optimistic: true  
    initial_value: 70
    restore_value: true
    on_value: 
      then:
        - script.execute: soc_check_alarm

light:
  - platform: rgb #Individual control of RGB elemenst of LED strip driven from AT Mega via this unit
    name: "ATMega RGB Light"
    id: ainsley_rgb_light
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0s #instant change of colour as we cannot cope with transitions
    restore_mode: RESTORE_DEFAULT_OFF

switch: 
  - platform: template
    id: relay_1
    name: "ATMega Relay 1"
    turn_on_action:
      - uart.write: [0x52, 0x31, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_1
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x31, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_1
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_2
    name: "ATMega Relay 2"
    turn_on_action:
      - uart.write: [0x52, 0x32, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_2
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x32, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_2
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_3
    name: "ATMega Relay 3"
    turn_on_action:
      - uart.write: [0x52, 0x33, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_3
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x33, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_3
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_4
    name: "ATMega Relay 4"
    turn_on_action:
      - uart.write: [0x52, 0x34, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_4
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x34, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_4
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_5
    name: "ATMega Relay 5"
    turn_on_action:
      - uart.write: [0x52, 0x35, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_5
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x35, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_5
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_6
    name: "ATMega Relay 6"
    turn_on_action:
      - uart.write: [0x52, 0x36, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_6
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x36, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_6
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

# Only want climate control in main unit (state will be mirrored to monitor units)
climate:
  - platform: bang_bang
    id: climate_radiator
    name: "Engine -> Radiator Controller"
    sensor: vt_temp1 #Water Cylinder Top Temperature
    default_target_temperature_low: 50 °C
    default_target_temperature_high: 55 °C
    cool_action:
      - switch.turn_on: relay_1
    idle_action:
      - switch.turn_off: relay_1
    visual:
      min_temperature: 30
      max_temperature: 80
      temperature_step: 1

sensor: 
  - platform: mqtt_subscribe #copy in the speed from the receiver Fire unit
    topic: ${esphome_monitor}/sensor/speed_mph/state #Monitor state of another device
    disabled_by_default: True
    name: "Speed mph copy"
    id: speed_mph
    unit_of_measurement: "mph"
    device_class: speed
    accuracy_decimals: 1
    on_value:
      then:
        - script.execute: speed_mph_update 

  - platform: mqtt_subscribe #copy in the efficiency from the receiver Fire unit
    topic: ${esphome_monitor}/sensor/fuel_efficiency/state #Monitor state of another device
    name: "Fuel Efficiency copy"
    id: fuel_efficiency
    unit_of_measurement: "mpg"
    device_class: energy
    accuracy_decimals: 1
    on_value:
      then:
        - script.execute: fuel_efficiency_update
