# Specific code for the Home Assistant Boat Monitor unit that just mirrors the main unit goes in here
# Uses some dummy template MQTT sensors to receive the published info from main unit.
# Tricky part was the relay controls which also now publish as though they were main unit if teh buttons are pressed in lvgl screen

esphome:
  name: ${esphome_name}

number:
  - platform: template
    disabled_by_default: True #Hide device in Home Assistant as this just receives values set on main unit
    command_topic: ${esphome_source}/number/soc_warning_level/command #Monitor state of another device
    id: soc_warn_level
    name: "SOC warning level"
    max_value: 100
    min_value: 0
    step: 1
    optimistic: true  
    initial_value: 85
    restore_value: true
    on_value: 
      then:
        - script.execute: soc_check_alarm
  - platform: template
    disabled_by_default: True #Hide device in Home Assistant
    command_topic: ${esphome_source}/number/soc_alarm_level/command #Monitor state of another device
    id: soc_alarm_level
    name: "SOC alarm level"
    max_value: 100
    min_value: 0
    step: 1
    optimistic: true  
    initial_value: 70
    restore_value: true
    on_value: 
      then:
        - script.execute: soc_check_alarm
  - platform: template
    id: update_interval_gps
    name: "GPS Update Interval"
    optimistic: true  
    min_value: 5 #seconds
    max_value: 600
    initial_value: 60
    unit_of_measurement: "s"
    step: 5
    mode: slider
    on_value: 
      then:
        - lambda: |- 
            if (id(mqtt_client)->is_connected()) {
              int update_interval = id(update_interval_gps).state;
              if (update_interval < 2) {
                update_interval = 2; //Minimum interval of 5 seconds as a safety precaution
              }
              update_interval = update_interval * 1000; //Convert to milliseconds !!!!
              id(gps_receiver).set_update_interval(update_interval);
              id(gps_receiver).call_setup(); //Force immediate update with new interval
            }

#Only fit GPS unit to the receiver Fire unit
gps:
  id: gps_receiver
  latitude:
    id: gps_latitude
    name: "Latitude"
    filters: #noisy signal so average it out
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
  longitude:
    id: gps_longitude
    name: "Longitude"
    filters: #noisy signal so average it out
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5
  altitude:
    id: gps_altitude
    name: "Altitude"
    filters: #Altitude is very noisy signal so average it out
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
  speed:
    id: gps_speed_kmh
    name: "Speed"
    internal: true
  course:
    id: gps_course
    name: "Course"
  satellites:
    id: gps_satelites
    name: "Satellites"
  hdop:
    id: gps_hdop
    name: "HDOP"
    device_class: distance
    unit_of_measurement: "m"
  update_interval: ${update_interval_speed}
  uart_id: uart_bus
# Note in HA these are combined into a position sensor using a template sensor with multiple attributes

sensor:
  - platform: template
    name: "Speed mph"
    id: speed_mph
    unit_of_measurement: "mph"
    device_class: speed
    accuracy_decimals: 1
    update_interval: ${update_interval_speed}
    lambda: |-
      if (id(gps_speed_kmh).state < 0.4) return 0; //Ignore low speeds as these are just noise
      return id(gps_speed_kmh).state * 0.621371;
    on_value:
      then:
        - lvgl.indicator.update:
            id: speed_needle
            value: !lambda 'return (id(speed_mph).state)*100; //Scale value as meter only copes with integers' 
        - lvgl.label.update:
            id: lbl_speed_dial
            text:
              format: "%.1f"
              args: [ 'id(speed_mph).state' ]
        - lvgl.label.update:
            id: lbl_rpm_lbl_speed
            text:
              format: "mph:\n%.1f"
              args: [ 'id(speed_mph).state' ]


light:
  - platform: rgb #Individual control of RGB elemenst of LED strip driven from AT Mega via this unit
    name: "ATMega RGB Light"
    id: ainsley_rgb_light
    internal: true #Don't want this in HA as controlled by main unit
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0s #instant change of colour as we cannot cope with transitions
    restore_mode: RESTORE_DEFAULT_OFF

# Same code as main unit really but adds a MQTT publish simulating main unit if buttons checked on lvgl screen
switch: 
  - platform: template
    id: relay_1
    name: "ATMega Relay 1"
    disabled_by_default: True #Hide device in Home Assistant as nternal does't work for MQTT
    command_topic: ${esphome_source}/switch/atmega_relay_1/state
    turn_on_action:
      - uart.write: [0x52, 0x31, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_1
          state:
            checked: True
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_1/command
          payload: "ON"      
    turn_off_action:
      - uart.write: [0x52, 0x31, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_1
          state:
            checked: False
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_1/command
          payload: "OFF"      
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_2
    name: "ATMega Relay 2"
    disabled_by_default: True #Hide device in Home Assistant as nternal does't work for MQTT
    command_topic: ${esphome_source}/switch/atmega_relay_2/state
    turn_on_action:
      - uart.write: [0x52, 0x32, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_2
          state:
            checked: True
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_2/command
          payload: "ON"      
    turn_off_action:
      - uart.write: [0x52, 0x32, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_2
          state:
            checked: False
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_2/command
          payload: "OFF"      
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_3
    name: "ATMega Relay 3"
    disabled_by_default: True #Hide device in Home Assistant as nternal does't work for MQTT
    command_topic: ${esphome_source}/switch/atmega_relay_3/state
    turn_on_action:
      - uart.write: [0x52, 0x33, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_3
          state:
            checked: True
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_3/command
          payload: "ON"      
    turn_off_action:
      - uart.write: [0x52, 0x33, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_3
          state:
            checked: False
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_3/command
          payload: "OFF"      
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_4
    name: "ATMega Relay 4"
    disabled_by_default: True #Hide device in Home Assistant as nternal does't work for MQTT
    command_topic: ${esphome_source}/switch/atmega_relay_4/state
    turn_on_action:
      - uart.write: [0x52, 0x34, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_4
          state:
            checked: True
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_4/command
          payload: "ON"      
    turn_off_action:
      - uart.write: [0x52, 0x34, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_4
          state:
            checked: False
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_4/command
          payload: "OFF"      
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_5
    name: "ATMega Relay 5"
    disabled_by_default: True #Hide device in Home Assistant as nternal does't work for MQTT
    command_topic: ${esphome_source}/switch/atmega_relay_5/state
    turn_on_action:
      - uart.write: [0x52, 0x35, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_5
          state:
            checked: True
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_5/command
          payload: "ON"      
    turn_off_action:
      - uart.write: [0x52, 0x35, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_5
          state:
            checked: False
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_5/command
          payload: "OFF"      
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_6
    name: "ATMega Relay 6"
    disabled_by_default: True #Hide device in Home Assistant as nternal does't work for MQTT
    command_topic: ${esphome_source}/switch/atmega_relay_6/state
    turn_on_action:
      - uart.write: [0x52, 0x36, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_6
          state:
            checked: True
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_6/command
          payload: "ON"      
    turn_off_action:
      - uart.write: [0x52, 0x36, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_6
          state:
            checked: False
      - mqtt.publish:
          topic: ${esphome_source}/switch/atmega_relay_6/command
          payload: "OFF"      
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

# Don't want a conflicting climate control here - only use main Boat device
