# Specific code for the Home Assistant Boat Monitor main unit goes in here
#

esphome:
  name: ${esphome_name}


number:
  - platform: template
    id: soc_warn_level
    name: "SOC warning level"
    max_value: 100
    min_value: 0
    step: 1
    optimistic: true  
    initial_value: 85
    restore_value: true
    on_value: 
      then:
        - script.execute: soc_check_alarm
  - platform: template
    id: soc_alarm_level
    name: "SOC alarm level"
    max_value: 100
    min_value: 0
    step: 1
    optimistic: true  
    initial_value: 70
    restore_value: true
    on_value: 
      then:
        - script.execute: soc_check_alarm


switch: 
  - platform: template
    id: relay_1
    name: "ATMega Relay 1"
    turn_on_action:
      - uart.write: [0x52, 0x31, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_1
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x31, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_1
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_2
    name: "ATMega Relay 2"
    turn_on_action:
      - uart.write: [0x52, 0x32, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_2
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x32, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_2
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_3
    name: "ATMega Relay 3"
    turn_on_action:
      - uart.write: [0x52, 0x33, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_3
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x33, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_3
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_4
    name: "ATMega Relay 4"
    turn_on_action:
      - uart.write: [0x52, 0x34, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_4
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x34, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_4
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_5
    name: "ATMega Relay 5"
    turn_on_action:
      - uart.write: [0x52, 0x35, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_5
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x35, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_5
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

  - platform: template
    id: relay_6
    name: "ATMega Relay 6"
    turn_on_action:
      - uart.write: [0x52, 0x36, 0x31, 0x0A, 0x0D] #Send Relay state to AT Mega R21\r\n
      - lvgl.widget.update:
          id: btn_relay_6
          state:
            checked: True
    turn_off_action:
      - uart.write: [0x52, 0x36, 0x30, 0x0A, 0x0D] #Send Relay state to AT Mega R20\r\n
      - lvgl.widget.update:
          id: btn_relay_6
          state:
            checked: False
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

# Only want climate control in main unit (state will be mirrored to monitor units)
climate:
  - platform: bang_bang
    id: climate_radiator
    name: "Engine -> Radiator Controller"
    sensor: vt_temp1 #Water Cylinder Top Temperature
    default_target_temperature_low: 50 °C
    default_target_temperature_high: 55 °C
    cool_action:
      - switch.turn_on: relay_1
    idle_action:
      - switch.turn_off: relay_1
    visual:
      min_temperature: 30
      max_temperature: 80
      temperature_step: 1