substitutions:
  devicename: m5cores3
  esphome_name: M5CoreS3
  sensor_update: 60s
  temp_bar_scale: "3.0"

esphome:
  name: ${devicename}
  friendly_name: ${esphome_name}

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    ## Note: Disable these configurations if you face the boot loop issue.
    sdkconfig_options:
        CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
        CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
        CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
        # Moves instructions and read only data from flash into PSRAM on boot.
        # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
        # Considerably speeds up mWW at the cost of using more PSRAM.
        CONFIG_SPIRAM_RODATA: "y"
        CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

psram:
  mode: quad
  speed: 80MHz

packages:
  wifi: !include wifi.yaml
  lvgl: !include lvglCore3.yaml
  mqtt: !include mqtt.yaml

logger:
  level: DEBUG

# Enable Home Assistant API
api:
  reboot_timeout: 0s #disable reboots whilst we recode everything to use mqtt
  encryption:
    key: !secret api_encryption
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.hide: boot_screen
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));'
        then:
          - lvgl.widget.show: boot_screen

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: [axp2101, aw88298, aw9523b ]

i2c:
  - id: bus_internal
    sda: GPIO12
    scl: GPIO11

spi:
  - id: spi_bus
    clk_pin: GPIO36
    mosi_pin: GPIO37

axp2101:
  id: axp2101_pmu
  i2c_id: bus_internal

# IO Expander
aw9523b:
  - id: aw9523b_hub
    i2c_id: bus_internal

output:
  - platform: axp2101
    type: range
    channel: DLDO1
    id: lcd_backlight_output
    min_voltage: 2600
    max_voltage: 3300

  - platform: axp2101
    channel: ALDO1
    voltage: 1800

  - platform: axp2101
    channel: ALDO2
    voltage: 3300

  - platform: axp2101
    channel: BLDO1
    voltage: 2800

  - platform: axp2101
    channel: BLDO2
    voltage: 1500

touchscreen:
  - platform: ft63x6
    id: touch
    reset_pin:
      aw9523b: aw9523b_hub
      number: 0
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 240

display:
  - platform: mipi_spi
    model: M5CORE
    dc_pin: GPIO35
    reset_pin:
      aw9523b: aw9523b_hub
      number: 9
    cs_pin: 
      number: GPIO3
      ignore_strapping_warning: true
    data_rate: 40MHz
    invert_colors: true
    id: m5cores3_lcd
    # show_test_card: true

light:
  - platform: monochromatic
    id: lcd_backlight
    name: "LCD Backlight"
    icon: "mdi:television"
    entity_category: config
    output: lcd_backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

#=========================================================================================================
binary_sensor:
  - platform: homeassistant
    id: heating_pump
    entity_id: switch.heating_pump_switch_1
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: btn_heating_pump
          state:
            checked: !lambda return x;

# some aw9523b inputs (handle interrupts)
# and other binary sensors
  # - platform: gpio
  #   name: "ES_INT P0_3"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 3
  #   on_press:
  #     then:
  #       - logger.log: "ES7210 interrupt triggered"
  #   internal: true

  # - platform: gpio
  #   name: "TF_SW P0_4"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 4 
  #   on_press:
  #     then:
  #       - logger.log: "TF_SW interrupt triggered"
  #   internal: true
  
  # - platform: gpio
  #   name: "TOUCH_INT P1_2"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 10
  #   on_press:
  #     then:
  #       - logger.log: "TOUCH interrupt triggered"
  #   internal: true

  # - platform: gpio
  #   name: "AW_INT P1_3"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 11
  #   on_press:
  #     then:
  #       - logger.log: "AW88298 interrupt triggered"
  #   internal: true

#=========================================================================================================
sensor:
# PMU
  - platform: axp2101
    id: axp2101_sensor
    battery_level:
      name: "Battery Level"
    battery_voltage:
      name: "Battery Voltage"
    axp_temperature:
      name: "AXP2101 Temperature"
    battery_charging:
      name: "Battery Charging"

  - platform: homeassistant
    id: t_h_jim_study_temperature
    entity_id: sensor.t_h_jim_study_temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_jim_study_temp
            text:
              format: "Jim Study: %.1f°C"
              args: [ 'id(t_h_jim_study_temperature).state' ]
        - lvgl.bar.update:
            id: bar_jim_study_temp
            value: !lambda 'return (id(t_h_jim_study_temperature).state) * $temp_bar_scale;'
  - platform: homeassistant
    id: t_h_sue_study_temperature
    entity_id: sensor.t_h_sue_study_temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_sue_study_temp
            text:
              format: "Sue Study: %.1f°C"
              args: [ 'id(t_h_sue_study_temperature).state' ]
        - lvgl.bar.update:
            id: bar_sue_study_temp
            value: !lambda 'return (id(t_h_sue_study_temperature).state) * $temp_bar_scale;'
  - platform: homeassistant
    id: t_h_kitchen_temperature
    entity_id: sensor.t_h_kitchen_temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_kitchen_temp
            text:
              format: "Kitchen: %.1f°C"
              args: [ 'id(t_h_kitchen_temperature).state' ]
        - lvgl.bar.update:
            id: bar_kitchen_temp
            value: !lambda 'return (id(t_h_kitchen_temperature).state) * $temp_bar_scale;'
  - platform: homeassistant
    id: t_h_lounge_temperature
    entity_id: sensor.t_h_lounge_temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_lounge_temp
            text:
              format: "Lounge: %.1f°C"
              args: [ 'id(t_h_lounge_temperature).state' ]
        - lvgl.bar.update:
            id: bar_lounge_temp
            value: !lambda 'return (id(t_h_lounge_temperature).state) * $temp_bar_scale;'
  - platform: homeassistant
    id: t_h_hall_temperature
    entity_id: sensor.t_h_hall_temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_hall_temp
            text:
              format: "Hall: %.1f°C"
              args: [ 'id(t_h_hall_temperature).state' ]
        - lvgl.bar.update:
            id: bar_hall_temp
            value: !lambda 'return (id(t_h_hall_temperature).state) * $temp_bar_scale;'
  - platform: homeassistant
    id: t_h_spare_room_temperature
    entity_id: sensor.t_h_spare_room_temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_spare_rm_temp
            text:
              format: "Spare Rm: %.1f°C"
              args: [ 'id(t_h_spare_room_temperature).state' ]
        - lvgl.bar.update:
            id: bar_spare_rm_temp
            value: !lambda 'return (id(t_h_spare_room_temperature).state) * $temp_bar_scale;'
  - platform: homeassistant
    id: t_h_main_bed_rm_temperature
    entity_id: sensor.temperature_humidity_sensor_8_temperature
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_main_bed_rm_temp
            text:
              format: "Main BedRm: %.1f°C"
              args: [ 'id(t_h_main_bed_rm_temperature).state' ]
        - lvgl.bar.update:
            id: bar_main_bed_rm_temp
            value: !lambda 'return (id(t_h_main_bed_rm_temperature).state) * $temp_bar_scale;'
  - platform: homeassistant
    id: t_h_jim_study_humidity
    entity_id: sensor.t_h_jim_study_humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_jim_study_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_jim_study_humidity).state' ]  
        - lvgl.bar.update:
            id: bar_jim_study_humidity
            value: !lambda 'return id(t_h_jim_study_humidity).state;'
  - platform: homeassistant
    id: t_h_sue_study_humidity
    entity_id: sensor.t_h_sue_study_humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_sue_study_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_sue_study_humidity).state' ]
        - lvgl.bar.update:  
            id: bar_sue_study_humidity
            value: !lambda 'return id(t_h_sue_study_humidity).state;'
  - platform: homeassistant
    id: t_h_kitchen_humidity
    entity_id: sensor.t_h_kitchen_humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_kitchen_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_kitchen_humidity).state' ]
        - lvgl.bar.update:  
            id: bar_kitchen_humidity
            value: !lambda 'return id(t_h_kitchen_humidity).state;'
  - platform: homeassistant
    id: t_h_lounge_humidity
    entity_id: sensor.t_h_lounge_humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_lounge_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_lounge_humidity).state' ]
        - lvgl.bar.update:
            id: bar_lounge_humidity
            value: !lambda 'return id(t_h_lounge_humidity).state;'
  - platform: homeassistant
    id: t_h_hall_humidity
    entity_id: sensor.t_h_hall_humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_hall_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_hall_humidity).state' ]
        - lvgl.bar.update:
            id: bar_hall_humidity
            value: !lambda 'return id(t_h_hall_humidity).state;'
  - platform: homeassistant
    id: t_h_spare_room_humidity
    entity_id: sensor.t_h_spare_room_humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_spare_rm_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_spare_room_humidity).state' ]
        - lvgl.bar.update:
            id: bar_spare_rm_humidity
            value: !lambda 'return id(t_h_spare_room_humidity).state;'
  - platform: homeassistant
    id: t_h_main_bed_rm_humidity
    entity_id: sensor.temperature_humidity_sensor_8_humidity
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_main_bed_rm_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_main_bed_rm_humidity).state' ]
        - lvgl.bar.update:    
            id: bar_main_bed_rm_humidity
            value: !lambda 'return id(t_h_main_bed_rm_humidity).state;'