substitutions:
  devicename: m5core2
  upper_devicename: M5Core2

esphome:
  name: $devicename
  platformio_options:
    upload_speed: 460800

esp32:
  board: m5stack-core-esp32 #m5stack-core2
  framework:
    # type: arduino 
    type: esp-idf
  flash_size: 16MB # Need to manually override defaults so M5STACK FIRE memory

psram:
  mode: quad
  speed: 80MHz

packages:
#  m5stackfire: !include M5StackCore2.yaml
#  wifi: !include wifi.yaml
  lvgl: !include lvglCore2.yaml

external_components:
  - source:
      type: git
      url: https://github.com/JensGuckenbiehl/esphome-m5core2.git
    refresh: 0s

axp192:
  id: axp
  model: M5CORE2
  address: 0x34
  i2c_id: bus_a
#  update_interval: 60s

wifi:
  # output_power: 8.5  
  networks:
    # - ssid: !secret wifi_comp_ssid
    #   password: !secret wifi_comp_password
    - ssid: !secret wifi_home_ssid
      password: !secret wifi_home_password
    # - ssid: !secret wifi_phone_ssid
    #   password: !secret wifi_phone_password
    # - ssid: !secret wifi_bshed_ssid
    #   password: !secret wifi_bshed_password

logger:
  level: DEBUG

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

sensor:
  # - platform: axp
  #   model: M5CORE2
  #   address: 0x34
  #   i2c_id: bus_a
  #   update_interval: 30s
  #   battery_level:
  #     name: "${upper_devicename} Battery Level"
  #     id: "${devicename}_batterylevel"

  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    id: wifi_dbm
  - platform: uptime
    name: ${upper_devicename} Uptime

display:
  - platform: ili9xxx
    id: m5stack_display #320x240 pixels
    model: ili9342
    cs_pin: GPIO5
    dc_pin: GPIO15
    invert_colors: true
    show_test_card: true
    auto_clear_enabled: false
    dimensions:
      width: 320
      height: 240
    transform:
      mirror_x: false # must be explicitly included, otherwise it defaults to true with the ili9342

touchscreen:
  - platform: ft63x6
    interrupt_pin: GPIO39

binary_sensor:
  # the virtual buttons--coordinates taken from
  # https://github.com/m5stack/M5Core2/blob/0134dd3a38cfd335a1ec39da2c149f88baf54326/src/M5Core2.h#L54-L56
  # and
  # https://github.com/m5stack/M5Core2/blob/0134dd3a38cfd335a1ec39da2c149f88baf54326/src/utility/M5Button.h#L811-L815
  # for the parameter order `(x, y, width, height)`
  - platform: touchscreen
    name: Button A
    id: M5_BtnA
    x_min: 10
    x_max: 120
    y_min: 240
    y_max: 280
#    use_raw: true
    # on_double_click:
    #   then: # Focus on top level buttons at bottom (of this page)
    #     - lvgl.widget.focus: top_layer

  - platform: touchscreen
    name: Button B
    id: M5_BtnB
    x_min: 130
    x_max: 200
    y_min: 240
    y_max: 280
#    use_raw: true
    # on_double_click:
    #   then: # Return to Home screen with focus on top level button for "next page" at bottom
    #     - lvgl.page.show: main_page
    #     - lvgl.widget.focus: page_next

  - platform: touchscreen
    name: Button C
    id: M5_BtnC
    x_min: 230
    x_max: 310
    y_min: 240
    y_max: 280
#    use_raw: true
# doesn't work:
# i2s_audio:
#   id: bus_i2s
#   i2s_lrclk_pin: GPIO0
#   i2s_bclk_pin: GPIO12
# speaker:
#   - platform: i2s_audio
#     dac_type: external
#     i2s_dout_pin: GPIO2
#     sample_rate: 44100
#     bits_per_sample: 16bit
# now use it:
# on_...:
#   then:
#     # turn on the power for gpio0-2
#     - lambda: |-
#         id(axp192_id).Write1Byte(0x94, id(axp192_id).Read8bit(0x94) | 0x07);
#     - speaker.volume_set: 50%
#     - speaker.play:
#         data: !lambda return startup_raw;