# Stub file that simply defines specific unit name for a AQI Sensor system on a M5Stack Fire Unit

substitutions:
  friendly_name: "Fire4" #Jim Office
  esphome_name: "fire4"

esphome:
  name: ${esphome_name}

packages:
  boat: !include FireAQI.yaml