# All code for the Battery Monitor goes in here
# This file in turn is included in a very empty stub file that just defines the device names
# Expects LoRa comms back to a FireAQI unit acting as a relay to HA via MQTT 
# for WiFi /MQTT communication back to Home Assistant server
#
substitutions:
  sensor_update: 60s

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -100 #Ensure this runs after lvgl is initialised
      then:
        # - delay: 10s

packages:
  wifi: !include wifi.yaml
  mqtt: !include mqtt.yaml
  lvgl: !include lvglBattMon.yaml
  lvglcommon: !include lvglcommon.yaml

mqtt:
  reboot_timeout: 0s   #Disable automatic reboot on MQTT connection failure as usually we won't be on WiFi
  
wifi:
  reboot_timeout: 0s   #Disable automatic reboot on WiFi connection failure as usually we won't be on WiFi

#Note sure if this section is reqd
external_components:
  - source: #Restores functionality of Custom Components from ESPHome 2024.12.4
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
  - source:
      type: git
      url: https://github.com/ssieb/custom_components #used Custom Components

# Enable logging
logger:
  logs:
    component: DEBUG #Supress excessive warnings about display writing

time:
  - platform: sntp 
    id: sntp_time
    on_time: #Automation to enable display screen saver
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update #Updates time in top_level lvgl display
    on_time_sync:
      - script.execute: time_update

debug:
  update_interval: 60s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# Enable this sensor to track memory leak issues
sensor:
  - platform: debug
    free:
      name: "Heap Free"
      state_class: "measurement"
    min_free:
      name: "Heap Min Free"
      state_class: "measurement"
    loop_time:
      name: "Loop Time"
      state_class: "measurement"
    # psram:
    #   name: "Free PSRAM"
