substitutions:
  friendly_name: "Boat2"
  esphome_name: "fireboat2"
  esphome_source: "fireboat" #esphome_name of source sensor data that we will mirror on this device

esphome:
  name: ${esphome_name}
  build_path: C:/EsphomeTemp/${esphome_name}

packages:
  common: !include BoatCommon.yaml
  boat: !include BoatReceive.yaml
  uart: !include FireNoUartex.yaml
  m5stackfire: !include M5StackFire.yaml

# Need to specify Uart settings per device as they now change for different GPS units
uart:
  id: uart_bus
  baud_rate: 9600 # 115200 for M5Stack GPS V2.1 or 9600 for M5Stack GPS V1 or ATMega Unit
  data_bits: 8
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO26 #TXD2 M5Stack Fire
  rx_pin: GPIO36 #RXD2 on M5Stack Fire

