# All common code for the Home Assistant Boat Monitor goes in here
# This file in turn is included in a very empty stub file that just defines the device names
# Unit designed to have a serial input on rx_pin from teh ATMega 2560 unit that is doing the sensor monitoring and sending back simple update sto this unit
# for WiFi /MQTT communication back to Home Assistant server
#
substitutions:
  sensor_update: 60s

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -100 #Ensure this runs after lvgl is initialised
      then:
        - delay: 8s
        - lvgl.widget.hide: boot_screen

packages:
  m5stackfire: !include M5StackFire.yaml
  wifi: !include wifi.yaml
  mqtt: !include mqttaqi.yaml
  lvgl: !include lvglminimal.yaml
  bme68x: !include BME68x.yaml
  pmsa003i: !include pmsa003i.yaml
  # mics6814: !include MICS6814.yaml
  scd30: !include scd30.yaml

# mqtt:
#   on_message: 
#     - topic: ${esphome_name}/scd30_calibrate
#       then:
#         - button.press: scd30_calibrate

external_components:
  - source: #Restores functionality of Custom Components from ESPHome 2024.12.4
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
  - source:
      type: git
      url: https://github.com/ssieb/custom_components #used Custom Components

# Enable logging
logger:
  logs:
    component: DEBUG #Supress excessive warnings about display writing
  
# captive_portal:

time:
  - platform: sntp 
    id: sntp_time
    on_time: #Automation to enable display screen saver
      # - hours: 2,3,4,5
      #   minutes: 5
      #   seconds: 0
      #   then:
      #     - switch.turn_on: switch_antiburn
      # - hours: 2,3,4,5
      #   minutes: 35
      #   seconds: 0
      #   then:
      #     - switch.turn_off: switch_antiburn
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update #Updates time in top_level lvgl display
    on_time_sync:
      - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: lbl_time
          text: 
            format: "%s"
            args: [ 'id(sntp_time).now().strftime("%R").c_str()' ]

debug:
  update_interval: 60s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

# Enable this sensor to track memory leak issues
sensor:
  - platform: debug
    free:
      name: "Heap Free"
    loop_time:
      name: "Loop Time"
    # psram:
    #   name: "Free PSRAM"
