substitutions:
  friendly_name: "FireGPS" #AINSLEY GPS
  esphome_name: "firegps"
  sensor_update: 60s
  update_interval_speed: 5s
  tx_pin: GPIO26 #TXD2 M5Stack Fire
  rx_pin: GPIO36 #GPIO36 #RXD2 on M5Stack Fire

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -100 #Ensure this runs after lvgl is initialised
      then:
        - delay: 8s
        - lvgl.widget.hide: boot_screen

packages:
  m5stackfire: !include M5StackFire.yaml
  wifi: !include wifi.yaml
  mqtt: !include mqtt.yaml
  lvgl: !include lvglGPS.yaml

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ ip5306 ]

# Enable logging
logger:
  logs:
    component: DEBUG #Supress excessive warnings about display writing
  

time:
  - platform: sntp 
    id: sntp_time
    on_time: #Automation to enable display screen saver
      # - hours: 2,3,4,5
      #   minutes: 5
      #   seconds: 0
      #   then:
      #     - switch.turn_on: switch_antiburn
      # - hours: 2,3,4,5
      #   minutes: 35
      #   seconds: 0
      #   then:
      #     - switch.turn_off: switch_antiburn
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update #Updates time in top_level lvgl display
    on_time_sync:
      - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.label.update:
          id: lbl_time
          text: 
            format: "%s"
            args: [ 'id(sntp_time).now().strftime("%R").c_str()' ]

uart:
  id: uart_bus
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 9600

gps:
  latitude:
    id: gps_latitude
    name: "Latitude"
  longitude:
    id: gps_longitude
    name: "Longitude"
  altitude:
    id: gps_altitude
    name: "Altitude"
  speed:
    id: gps_speed_kmh
    name: "Speed"
  course:
    id: gps_course
    name: "Course"
  satellites:
    id: pgs_satelites
    name: "Satellites"
  hdop:
    id: gps_hdop
    name: "HDOP"
    device_class: distance
    unit_of_measurement: "m"
  update_interval: ${update_interval_speed}
  uart_id: uart_bus
# Note in HA these are combined into a position sensor using a template sensor with multiple attributes


sensor:
  - platform: template
    name: "Speed mph"
    id: speed_mph
    unit_of_measurement: "mph"
    device_class: speed
    accuracy_decimals: 1
    update_interval: ${update_interval_speed}
    lambda: |-
      if (id(gps_speed_kmh).state < 0.4) return 0; //Ignore low speeds as these are just noise
      return id(gps_speed_kmh).state * 0.621371;
    on_value:
      then:
        - lvgl.indicator.update:
            id: speed_needle
            value: !lambda 'return (id(speed_mph).state)*100; //Scale value as meter only copes with integers' 
        - lvgl.label.update:
            id: lbl_speed_dial
            text:
              format: "%.1f"
              args: [ 'id(speed_mph).state' ]
    