# All common code for the Home Assistant AQI Monitor goes in here
# This file in turn is included in a very empty stub file that just defines the device names
# 
# for WiFi /MQTT communication back to Home Assistant server
#
substitutions:
  sensor_update: 60s

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -100 #Ensure this runs after lvgl is initialised
      then:
        # - delay: 10s
        # - switch.turn_on: calibration_switch # Run a calibration on bootup for MCS6814

packages:
  wifi: !include wifi.yaml
  mqtt: !include mqtt.yaml
  lvgl: !include lvglAQI.yaml
  lvglcommon: !include lvglcommon.yaml
  bme68x: !include BME68x.yaml
  pmsa003i: !include pmsa003i.yaml
  # mics6814: !include MICS6814.yaml
  scd30: !include scd30.yaml
# mqtt:
#   on_message: 
#     - topic: ${esphome_name}/scd30_calibrate
#       then:
#         - button.press: scd30_calibrate

external_components:
  - source: #Restores functionality of Custom Components from ESPHome 2024.12.4
      type: git
      url: https://github.com/robertklep/esphome-custom-component
    components: [ custom, custom_component ]
  - source:
      type: git
      url: https://github.com/ssieb/custom_components #used Custom Components

# Enable logging
logger:
  logs:
    component: DEBUG #Supress excessive warnings about display writing

time:
  - platform: sntp 
    id: sntp_time
    on_time: #Automation to enable display screen saver
      # - hours: 2,3,4,5
      #   minutes: 5
      #   seconds: 0
      #   then:
      #     - switch.turn_on: switch_antiburn
      # - hours: 2,3,4,5
      #   minutes: 35
      #   seconds: 0
      #   then:
      #     - switch.turn_off: switch_antiburn
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update #Updates time in top_level lvgl display
    on_time_sync:
      - script.execute: time_update

debug:
  update_interval: 60s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_newsfeed
    topic: homeassistant/climate_newsfeed/state
    on_value: #When value changes update LVGL display
      - logger.log: "Climate newsfeed updated"
      - lvgl.label.update:
          id: lbl_scrolling_news
          text:
            format: " %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |"
            # args: [ id(climate_headline_0).state.c_str() ]
            # format: "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s "
            args: [ id(climate_headline_0).state.c_str() , id(climate_headline_1).state.c_str() , id(climate_headline_2).state.c_str() , id(climate_headline_3).state.c_str() , id(climate_headline_4).state.c_str() , id(climate_headline_5).state.c_str() , id(climate_headline_6).state.c_str() , id(climate_headline_7).state.c_str() , id(climate_headline_8).state.c_str() , id(climate_headline_9).state.c_str() ]
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_0
    topic: homeassistant/climate_newsfeed/headline_0
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_1
    topic: homeassistant/climate_newsfeed/headline_1
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_2
    topic: homeassistant/climate_newsfeed/headline_2
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_3
    topic: homeassistant/climate_newsfeed/headline_3
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_4
    topic: homeassistant/climate_newsfeed/headline_4
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_5
    topic: homeassistant/climate_newsfeed/headline_5
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_6
    topic: homeassistant/climate_newsfeed/headline_6
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_7
    topic: homeassistant/climate_newsfeed/headline_7
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_8
    topic: homeassistant/climate_newsfeed/headline_8
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_9
    topic: homeassistant/climate_newsfeed/headline_9



# Enable this sensor to track memory leak issues
sensor:
  - platform: debug
    free:
      name: "Heap Free"
    loop_time:
      name: "Loop Time"
    # psram:
    #   name: "Free PSRAM"

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm10_max
    topic: homeassistant/aqi_thresholds/pm10_max
    on_value:
      - script.execute: update_bar_pm10
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm10_alarm
    topic: homeassistant/aqi_thresholds/pm10_alarm
    on_value:
      - script.execute: update_bar_pm10
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm10_warn
    topic: homeassistant/aqi_thresholds/pm10_warn
    on_value:
      - script.execute: update_bar_pm10

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm2_5_max
    topic: homeassistant/aqi_thresholds/pm2_5_max
    on_value:
      - script.execute: update_bar_pm2_5
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm2_5_alarm
    topic: homeassistant/aqi_thresholds/pm2_5_alarm
    on_value:
      - script.execute: update_bar_pm2_5
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm2_5_warn
    topic: homeassistant/aqi_thresholds/pm2_5_warn
    on_value:
      - script.execute: update_bar_pm2_5

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: no2_max
    topic: homeassistant/aqi_thresholds/no2_max
    on_value:
      - script.execute: update_bar_no2
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: no2_alarm
    topic: homeassistant/aqi_thresholds/no2_alarm
    on_value:
      - script.execute: update_bar_no2
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: no2_warn
    topic: homeassistant/aqi_thresholds/no2_warn
    on_value:
      - script.execute: update_bar_no2

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co_max
    topic: homeassistant/aqi_thresholds/co_max
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_co
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co_alarm
    topic: homeassistant/aqi_thresholds/co_alarm
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_co
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co_warn
    topic: homeassistant/aqi_thresholds/co_warn
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_co

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co2_max
    topic: homeassistant/aqi_thresholds/co2_max
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_co2
      - script.execute: update_bar_co2b
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co2_alarm
    topic: homeassistant/aqi_thresholds/co2_alarm
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_co2
      - script.execute: update_bar_co2b
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co2_warn
    topic: homeassistant/aqi_thresholds/co2_warn
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_co2
      - script.execute: update_bar_co2b

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: nh3_max
    topic: homeassistant/aqi_thresholds/nh3_max
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_nh3
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: nh3_alarm
    topic: homeassistant/aqi_thresholds/nh3_alarm
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_nh3
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: nh3_warn
    topic: homeassistant/aqi_thresholds/nh3_warn
    on_value: #When value changes update LVGL display
      - script.execute: update_bar_nh3
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: scd30_calibration_level
    topic: homeassistant/scd30_calibration/level

