# Stub file that simply defines specific unit name for a AQI Sensor system on a M5Stack Fire Unit

substitutions:
  friendly_name: "Fire2" #Banbury Shed
  esphome_name: "fire2"

esphome:
  name: ${esphome_name}
  build_path: C:/EsphomeTemp/${esphome_name}

packages:
  fireaqi: !include FireAQI.yaml
  m5stackfire: !include M5StackFire.yaml
