# Stub file that simply defines specific unit name for a Boat Sensor Monitor system on a M5Stack Fire Unit

substitutions:
  friendly_name: "Boat" #Main unit onboard AINSLEY - other units act as monitors following status of this device
  esphome_name: "fireboat"

esphome:
  name: ${esphome_name}

packages:
  common: !include BoatCommon.yaml
  boat: !include BoatSend.yaml
  uart: !include FireUartex.yaml
