# Settings for INA219 current sensor

esphome:
  name: ${esphome_name}

# Example configuration entry
sensor:
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.05 ohm
    current:
      id: ina219_current
      name: "INA219 Current"
      unit_of_measurement: "A"
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_batt_mon_i
              text: !lambda 'return std::to_string(x).c_str();' #Update LVGL display with current
    power:
      id: ina219_power  
      name: "INA219 Power"
      unit_of_measurement: "W"
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_batt_mon_pwr
              text: !lambda 'return std::to_string(x).c_str();' #Update LVGL display with power
    bus_voltage:    
      id: ina219_bus_voltage
      name: "INA219 Bus Voltage"
      unit_of_measurement: "V"
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_batt_mon_v
              text: !lambda 'return std::to_string(x).c_str();' #Update LVGL display with voltage
    shunt_voltage:
      id: ina219_shunt_voltage
      name: "INA219 Shunt Voltage"
      filters:
        - multiply: 1000 # convert to mV for display
      unit_of_measurement: "mV"
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_batt_mon_shnt
              text: !lambda 'return std::to_string(x).c_str();' #Update LVGL display with shunt voltage
        # Send all values when shunt  changes as one string to simplify Tx processing
          - script.execute:
              id: lora_tx_msg
            #   msg: !lambda 'return "@V=" + std::to_string(id(ina219_bus_voltage).state) + ", I=" + std::to_string(id(ina219_current).state) + ", P=" + std::to_string(id(ina219_power).state) + ", ShntV=" + std::to_string(id(ina219_shunt_voltage).state);'
              msg: !lambda 'return str_sprintf("@V= %0.2f, I= %0.3f, P= %0.2f, ShntmV= %0.2f", id(ina219_bus_voltage).state, id(ina219_current).state, id(ina219_power).state, id(ina219_shunt_voltage).state);'

    max_voltage: 32.0V
    max_current: 6.4A
    # update_interval: 300s
    update_interval: 30s


