esphome:
  name: ${esphome_name}

#==========================================================================================================================
lvgl:
  theme:
    label:
      text_font: montserrat_14 # set all your labels to use your custom defined font
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
#       focused:
# #        bg_color: 0x00cc00
#         border_color: 0xff0000
# #        bg_grad_dir: NONE
#         border_width: 4
    buttonmatrix:
#      bg_opa: COVER
      bg_opa: TRANSP
      border_color: 0x0077b3
      border_width: 0 #Must be same border width focussed and non-focussed otherwise buttons shift up from screen bottom when focussed
      text_color: 0xFFFFFF
      pad_all: 0
      # focused:
      #   # bg_color: 0x00cc00
      #   border_color: 0xff0000
      #   # bg_grad_dir: NONE
      #   border_width: 2
      items: # set all your buttonmatrix buttons to use your custom defined styles and font
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        text_font: montserrat_14
        pressed:
          bg_color: 0x006699
          bg_grad_color: 0x00334d
        checked:
          bg_color: 0x1d5f96
          bg_grad_color: 0x03324A
          text_color: 0x005580
        # focused:
        #   bg_color: 0x00cc00
        #   border_color: 0xff0000
        #   bg_grad_dir: NONE
        #   border_width: 2
        #   border_post: true
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      focused:
        # bg_color: 0x00cc00
        border_color: 0xff0000
        # bg_grad_dir: NONE
        border_width: 2
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: COVER
      bg_color: 0xcccaca
      bg_opa: COVER
      pad_all: 0
      pressed: #Occurs momentarily when changed value is accepted
        border_color: 0xff0000
        # bg_grad_dir: NONE
        border_width: 4
        border_opa: COVER
        bg_color: 0x00cc00 #only affects the background not covered by indicator bar
      # focused:
      #   border_color: 0xff0000
      #   # bg_grad_dir: NONE
      #   border_width: 2
      #   border_opa: COVER
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
        # focused:
        #   # bg_color: 0x00cc00
        #   border_color: 0xff0000
        #   # bg_grad_dir: NONE
        #   border_width: 2
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        # focused:
        #   bg_color: 0x00cc00
        #   border_color: 0xff0000
        #   bg_grad_dir: NONE
        #   border_width: 2
#==========================================================================================================================
#==========================================================================================================================
  pages:
#==========================================================================================================================
#--------------------------------------------------------------------------
    - id: heating_page
      bg_color: 0x000000 #black
      widgets:
        - obj:
            align: TOP_MID
            styles: header_footer
            widgets:
              - label:
                  text: "Heating Control"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF #white
        - obj: # a properly placed coontainer object for all these controls
            text_color: white
            align: CENTER
            width: 320
            height: 180 #240-(2*30) #Display area less header & footer
            pad_all: 0
            bg_opa: TRANSP #COVER
            border_opa: TRANSP
            # outline_width: 1 #debug top check we fill available space
            layout: # enable the GRID layout for the children widgets
              type: GRID # split the rows and the columns proportionally
              grid_columns: [FR(1), FR(1)] # equal
              grid_rows: [FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1)] # like percents
              pad_row: 4
              pad_column: 8
              multiple_widgets_per_cell: true  #Flag to overcome bug introduced when ESPHome started checking for overlaid widgets
            widgets:
              - button:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 0 # the corresponding cell
                  grid_cell_column_span: 2 #Span 2 columns
                  grid_cell_row_span: 2 #Span 2 rows
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: btn_heating_pump
                  checkable: true
                  checked:
                    bg_color: red
                    text_color: black
                    bg_grad_dir: NONE
                  on_value:
                    then:
                      - logger.log:
                          format: "Heating Pump button state: %d"
                          args: [ x ]
                  widgets:
                    - label:
                        align: center
                        text: "Heating"
                  on_click:
                    - homeassistant.action:
                        action: switch.toggle
                        data:
                          entity_id: switch.heating_pump_switch_1
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 2 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_jim_study_temp
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_temperature
                    - label:
                        id: lbl_jim_study_temp
                        text: "Jim Study"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_jim_study_humidity
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_humidity
                    - label:
                        id: lbl_jim_study_humidity
                        text: "Jim Study"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 2 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_hall_temp
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_temperature
                    - label:
                        id: lbl_hall_temp
                        text: "Hall"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_hall_humidity
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_humidity
                    - label:
                        id: lbl_hall_humidity
                        text: "Hall"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 4 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_sue_study_temp
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_temperature
                    - label:
                        id: lbl_sue_study_temp
                        text: "Sue Study"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 5 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_sue_study_humidity
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_humidity
                    - label:
                        id: lbl_sue_study_humidity
                        text: "Sue Study"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 4 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_spare_rm_temp
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_temperature
                    - label:
                        id: lbl_spare_rm_temp
                        text: "Spare Rm"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 5 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_spare_rm_humidity
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_humidity
                    - label:
                        id: lbl_spare_rm_humidity
                        text: "Spare Rm"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 6 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_main_bed_rm_temp
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_temperature
                    - label:
                        id: lbl_main_bed_rm_temp
                        text: "Main Bed"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 7 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_main_bed_rm_humidity
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_humidity
                    - label:
                        id: lbl_main_bed_rm_humidity
                        text: "Main Bed"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 8 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_kitchen_temp
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_temperature
                    - label:
                        id: lbl_kitchen_temp
                        text: "Kitchen"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 9 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_kitchen_humidity
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_humidity
                    - label:
                        id: lbl_kitchen_humidity
                        text: "Kitchen"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 8 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_lounge_temp
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_temperature
                    - label:
                        id: lbl_lounge_temp
                        text: "Lounge"
                        styles: lbl_temperature_humidity
              - obj:
                  styles: obj_temperature_humidity
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 9 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  widgets:
                    - bar:
                        id: bar_lounge_humidity
                        value: 100
                        styles: bar_temperature
                        indicator: 
                          styles: indicator_humidity
                    - label:
                        id: lbl_lounge_humidity
                        text: "Lounge"
                        styles: lbl_temperature_humidity
       
#==========================================================================================================================
