esphome:
  name: ${esphome_name}

#==========================================================================================================================
lvgl:
  pages:
#--------------------------------------------------------------------------
    - id: heating_page
      bg_color: 0x000000 #black
      widgets:
        - obj:
            align: TOP_MID
            styles: header_footer
            widgets:
              - label:
                  text: "Heating Control"
                  align: CENTER
                  text_align: CENTER
                  text_color: 0xFFFFFF #white
        - obj: # a properly placed coontainer object for all these controls
            text_color: white
            align: CENTER
            width: 320
            height: 180 #240-(2*30) #Display area less header & footer
            pad_all: 0
            bg_opa: TRANSP #COVER
            border_opa: TRANSP
            # outline_width: 1 #debug top check we fill available space
            layout: # enable the GRID layout for the children widgets
              type: GRID # split the rows and the columns proportionally
              grid_columns: [FR(1), FR(1)] # equal
              grid_rows: [FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1)] # like percents
              pad_row: 2
              pad_column: 2
              multiple_widgets_per_cell: true  #Flag to overcome bug introduced when ESPHome started checking for overlaid widgets
            widgets:
              - button:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 0 # the corresponding cell
                  grid_cell_column_span: 2 #Span 2 columns
                  grid_cell_row_span: 2 #Span 2 rows
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: btn_heating_pump
                  checkable: true
                  checked:
                    bg_color: red
                    text_color: black
                    bg_grad_dir: NONE
                  on_value:
                    then:
                      - logger.log:
                          format: "Heating Pump button state: %d"
                          args: [ x ]
                  on_click:
                    - switch.toggle: heating_pump
                  widgets:
                    - label:
                        text: "Heating Pump"
                        align: CENTER
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 2 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_jim_study_temp
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_temperature
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 2 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_jim_study_temp
                  text: "Jim Study"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_jim_study_humidity
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_humidity
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_jim_study_humidity
                  text: "Jim Study"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 2 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_hall_temp
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_temperature
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 2 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_hall_temp
                  text: "Hall"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_hall_humidity
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_humidity
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 3 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_hall_humidity
                  text: "Hall"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 4 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_sue_study_temp
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_temperature
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 4 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_sue_study_temp
                  text: "Sue Study"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 5 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_sue_study_humidity
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_humidity
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 5 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_sue_study_humidity
                  text: "Sue Study"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 4 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_spare_rm_temp
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_temperature
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 4 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_spare_rm_temp
                  text: "Spare Rm"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 5 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_spare_rm_humidity
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_humidity
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 5 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_spare_rm_humidity
                  text: "Spare Rm"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 6 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_main_bed_rm_temp
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_temperature
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 6 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_main_bed_rm_temp
                  text: "Main Bed"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 7 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_main_bed_rm_humidity
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_humidity
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 7 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_main_bed_rm_humidity
                  text: "Main Bed"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 8 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_kitchen_temp
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_temperature
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 8 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_kitchen_temp
                  text: "Kitchen"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 9 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_kitchen_humidity
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_humidity
              - label:
                  grid_cell_column_pos: 0 # place the widget in
                  grid_cell_row_pos: 9 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_kitchen_humidity
                  text: "Kitchen"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 8 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_lounge_temp
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_temperature
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 8 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_lounge_temp
                  text: "Lounge"
                  styles: lbl_temperature_humidity
              - bar:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 9 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: bar_lounge_humidity
                  value: 100
                  styles: bar_temperature
                  indicator: 
                    styles: indicator_humidity
              - label:
                  grid_cell_column_pos: 1 # place the widget in
                  grid_cell_row_pos: 9 # the corresponding cell
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  id: lbl_lounge_humidity
                  text: "Lounge"
                  styles: lbl_temperature_humidity
       
#==========================================================================================================================
