#Specific setup to run code on a M5STack Core2 V1 unit

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -100 #Ensure this runs after lvgl is initialised
      then:
        - delay: 4s
        - lvgl.widget.hide: boot_screen
        - delay: 20s # Give long enough for hardware to detect power state
        - script.execute: check_charger
        - script.execute: check_charge_level

esp32:
  board: m5stack-core2
  # board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    ## Note: Disable these configurations if you face the boot loop issue.
    sdkconfig_options:
        CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
        CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
        CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
        # Moves instructions and read only data from flash into PSRAM on boot.
        # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
        # Considerably speeds up mWW at the cost of using more PSRAM.
        CONFIG_SPIRAM_RODATA: "y"
        CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source: C:\Users\jims9\OneDrive\Documents\ESPComponents\esphome-yaml\components
  # - source: github://jimwsmith/esphome-yaml/components
    components: [ axp192 ]
    refresh: 0s

axp192:
  id: axp192_pmu
  i2c_id: bus_internal

i2c:
  - id: bus_internal
    sda: GPIO21
    scl: GPIO22
    scan: true

spi:
  - id: spi_bus
    clk_pin: GPIO18
    mosi_pin: GPIO23
    miso_pin: GPIO38

touchscreen:
  - platform: ft63x6
    id: touch
    # interrupt_pin: GPIO39
    # reset_pin:
    #   aw9523b: aw9523b_hub
    #   number: 0
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 240

binary_sensor:
  # the virtual buttons--coordinates taken from
  # https://github.com/m5stack/M5Core2/blob/0134dd3a38cfd335a1ec39da2c149f88baf54326/src/M5Core2.h#L54-L56
  # and
  # https://github.com/m5stack/M5Core2/blob/0134dd3a38cfd335a1ec39da2c149f88baf54326/src/utility/M5Button.h#L811-L815
  # for the parameter order `(x, y, width, height)`
  - platform: touchscreen
    name: Button A
    x_min: 10
    x_max: 120
    y_min: 240
    y_max: 280
    use_raw: true

  - platform: touchscreen
    name: Button B
    x_min: 130
    x_max: 200
    y_min: 240
    y_max: 280
    use_raw: true

  - platform: touchscreen
    name: Button C
    x_min: 230
    x_max: 310
    y_min: 240
    y_max: 280
    use_raw: true

sensor:
# PMU
  - platform: axp192
    update_interval: ${sensor_update}
    id: axp192_sensor
    # Optional calibration settings for battery level calculation, suggest chart your own device battery voltage and charge current to configure these
    battery_discharge_100pc_voltage: 3670 #Battery voltage level at which 100% charge is assumed (when not charging, or charging finished) in mV
    battery_discharge_0pc_voltage: 3200 #Battery voltage level at which 0% charge is assumed (when not charging, or charging finished) in mV
    battery_charge_100pc_current: 50 #Battery charge current at which 100% charge is assumed (when charging) in mA
    battery_charge_0pc_current: 430 #Battery charge current at which 0% charge is assumed (when charging) in mA
    battery_voltage:
      name: "Battery Voltage"
    usb_voltage:
      name: "USB Voltage"
    usb_current:
      name: "USB Current"
    vbus_voltage:
      name: "VBus Voltage"
    vbus_current:
      name: "VBus Current"
    internal_temperature:
      name: "Int Temp"
    battery_power:
      name: "Battery Power"
    battery_charge_current:
      name: "Batt Charge I"
    battery_discharge_current:
      name: "Batt Discharge I"
    aps_voltage:
      name: "APS Voltage"
    battery_charging:
      id: charger_connected
      name: "Battery Charging"
      entity_category: "diagnostic"
      on_state: #When value changes update LVGL display
      - script.execute: check_charger
    battery_level:
      name: "Battery Level"
      id: battery_percent
      on_value:
        - script.execute: check_charge_level
      # battery_discharge_0pc_voltage: 3000 #Battery voltagelevel at which 0% charge is assumed (when not charging, or charging finished) in mV
      # battery_discharge_100pc_voltage: 3670 #Battery voltage level at which 100% charge is assumed (when not charging, or charging finished) in mV
      # battery_charge_100pc_current: 60 #Battery charge current at which 100% charge is assumed (when charging) in mA
      # battery_charge_0pc_current: 420 #Battery charge current at which 0% charge is assumed (when charging) in mA
    usb_present:
      name: "USB Supply Present"
    usb_valid:
      name: "USB Supply Valid"
    vbus_present:
      name: "VBus Supply Present"
    vbus_valid:
      name: "VBus Supply Valid"
    battery_discharging:
      name: "Battery Discharging"
    over_temperature:
      name: "Over Temperature"
    battery_connected:
      name: "Battery Connected"
    battery_in_active_mode:
      name: "Battery in Active Mode"
    low_charge_current:
      name: "Charge current less than expected"

output:
  - platform: axp192
    type: range
    channel: DCDC3
    id: lcd_backlight_output
    min_voltage: 2100
    max_voltage: 3500

  - platform: axp192
    channel: DLDO3
    id: vibration_motor
    voltage: 3300

  - platform: axp192
    channel: DLDO2
    id: lcd_power
    voltage: 3000

display:
  - platform: mipi_spi
    model: M5CORE2
    dc_pin:
      number: GPIO15
      ignore_strapping_warning: true
#     reset_pin:
#       aw9523b: aw9523b_hub
#       number: 9
    cs_pin: 
      number: GPIO5
      ignore_strapping_warning: true
    data_rate: 40MHz
    invert_colors: true
    id: m5core_lcd
    show_test_card: true

light:
  - platform: monochromatic
    id: display_backlight
    name: "LCD Backlight"
    icon: "mdi:television"
    entity_category: config
    output: lcd_backlight_output
    restore_mode: ALWAYS_ON #Always want to have a backlight on when we boot up
    default_transition_length: 250ms
  - platform: binary
    name: "Vibration"
    output: vibration_motor
  - platform: binary
    name: "LCD Power"
    output: lcd_power
    restore_mode: ALWAYS_ON #Always want to have a display on when we boot up

switch:
  - platform: axp192
    led_pwr:
      name: "Green LED"
    vibration_motor:
      name: "Vibration Motor"

#=========================================================================================================

lvgl:
  theme:
    label:
      text_font: montserrat_18 # set all your labels to use your custom defined font
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 2
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
#       focused:
# #        bg_color: 0x00cc00
#         border_color: 0xff0000
# #        bg_grad_dir: NONE
#         border_width: 4
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      # focused:
      #   # bg_color: 0x00cc00
      #   border_color: 0xff0000
      #   # bg_grad_dir: NONE
      #   border_width: 2
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: COVER
      bg_color: 0xcccaca
      bg_opa: COVER
      pad_all: 0
      pressed: #Occurs momentarily when changed value is accepted
        border_color: 0xff0000
        # bg_grad_dir: NONE
        border_width: 4
        border_opa: COVER
        bg_color: 0x00cc00 #only affects the background not covered by indicator bar
      # focused:
      #   border_color: 0xff0000
      #   # bg_grad_dir: NONE
      #   border_width: 2
      #   border_opa: COVER
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
        focused:
          # bg_color: 0x00cc00
          border_color: 0xff0000
          # bg_grad_dir: NONE
          border_width: 2
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        # focused:
        #   bg_color: 0x00cc00
        #   border_color: 0xff0000
        #   bg_grad_dir: NONE
        #   border_width: 2
#==========================================================================================================================
