substitutions:
  friendly_name: Heating
  esphome_name: m5cores3
  sensor_update: 60s
  temp_bar_scale: "3.0"

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  build_path: C:/EsphomeTemp/${esphome_name}
  on_boot:
    - priority: -100 #Ensure this runs after lvgl is initialised
      then:
        - delay: 4s
        - lvgl.widget.hide: boot_screen
        - script.execute: check_charger
        - script.execute: check_charge_level

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    ## Note: Disable these configurations if you face the boot loop issue.
    sdkconfig_options:
        CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
        CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
        CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
        # Moves instructions and read only data from flash into PSRAM on boot.
        # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
        # Considerably speeds up mWW at the cost of using more PSRAM.
        CONFIG_SPIRAM_RODATA: "y"
        CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

psram:
  mode: quad
  speed: 80MHz

packages:
  wifi: !include wifi.yaml
  mqtt: !include mqtt.yaml
  lvgl: !include lvglCore3.yaml #include first so that the first page in here will be displayed on boot
  lvglcommon: !include lvglcommon.yaml

logger:
  level: DEBUG

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: [axp2101, aw88298, aw9523b ]

i2c:
  - id: bus_internal
    sda: GPIO12
    scl: GPIO11

spi:
  - id: spi_bus
    clk_pin: GPIO36
    mosi_pin: GPIO37

axp2101:
  id: axp2101_pmu
  i2c_id: bus_internal

# IO Expander
aw9523b:
  - id: aw9523b_hub
    i2c_id: bus_internal

output:
  - platform: axp2101
    type: range
    channel: DLDO1
    id: lcd_backlight_output
    min_voltage: 2600
    max_voltage: 3300

  - platform: axp2101
    channel: ALDO1
    voltage: 1800

  - platform: axp2101
    channel: ALDO2
    voltage: 3300

  - platform: axp2101
    channel: BLDO1
    voltage: 2800

  - platform: axp2101
    channel: BLDO2
    voltage: 1500

touchscreen:
  - platform: ft63x6
    id: touch
    reset_pin:
      aw9523b: aw9523b_hub
      number: 0
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 240

display:
  - platform: mipi_spi
    model: M5CORE
    dc_pin: GPIO35
    reset_pin:
      aw9523b: aw9523b_hub
      number: 9
    cs_pin: 
      number: GPIO3
      ignore_strapping_warning: true
    data_rate: 40MHz
    invert_colors: true
    id: m5core_lcd
    # show_test_card: true

light:
  - platform: monochromatic
    id: display_backlight
    name: "LCD Backlight"
    icon: "mdi:television"
    entity_category: config
    output: lcd_backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

time:
  - platform: sntp 
    id: sntp_time
    on_time: #Automation to enable display screen saver
      # - hours: 2,3,4,5
      #   minutes: 5
      #   seconds: 30
      #   then:
      #     - switch.turn_on: switch_antiburn
      # - hours: 2,3,4,5
      #   minutes: 35
      #   seconds: 30
      #   then:
      #     - switch.turn_off: switch_antiburn
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: time_update #Updates time in top_level lvgl display once a minute
    on_time_sync:
      - script.execute: time_update

#=========================================================================================================

switch: 
# Note thi sswitch ability to contol a HA switch relies on an Automation being configured in HA to monitor the MQTT command topic
  - platform: template
    internal: True
    id: heating_pump
    state_topic: homeassistant/switch/heating_pump_switch_1/state
    command_topic: homeassistant/switch/heating_pump_switch_1/state #We use external state to control this switch
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lvgl.widget.update:
          id: btn_heating_pump
          state:
            checked: True
      - mqtt.publish:
          topic: homeassistant/switch/heating_pump_switch_1/command
          payload: "ON"      
    turn_off_action:
      - lvgl.widget.update:
          id: btn_heating_pump
          state:
            checked: False
      - mqtt.publish:
          topic: homeassistant/switch/heating_pump_switch_1/command
          payload: "OFF"      
    optimistic: true #Required so that state change gets registered even though there is no actual comms back to ack the relay change

binary_sensor:

# some aw9523b inputs (handle interrupts)
# and other binary sensors
  # - platform: gpio
  #   name: "ES_INT P0_3"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 3
  #   on_press:
  #     then:
  #       - logger.log: "ES7210 interrupt triggered"
  #   internal: true

  # - platform: gpio
  #   name: "TF_SW P0_4"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 4 
  #   on_press:
  #     then:
  #       - logger.log: "TF_SW interrupt triggered"
  #   internal: true
  
  # - platform: gpio
  #   name: "TOUCH_INT P1_2"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 10
  #   on_press:
  #     then:
  #       - logger.log: "TOUCH interrupt triggered"
  #   internal: true

  # - platform: gpio
  #   name: "AW_INT P1_3"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 11
  #   on_press:
  #     then:
  #       - logger.log: "AW88298 interrupt triggered"
  #   internal: true

#=========================================================================================================
sensor:
# PMU
  - platform: axp2101
    id: axp2101_sensor
    battery_voltage:
      name: "Battery Voltage"
    axp_temperature:
      name: "AXP2101 Temperature"
    battery_charging:
      id: charger_connected
      name: "Battery Charging"
      entity_category: "diagnostic"
      on_state: #When value changes update LVGL display
      - script.execute: check_charge_level
    battery_level:
      name: "Battery Level"
      id: battery_percent
      on_value:
        - script.execute: check_charge_level

  - platform: mqtt_subscribe
    id: t_h_jim_study_temperature
    topic: homeassistant/sensor/t_h_jim_study_temperature/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_jim_study_temp
            text:
              format: "Jim Study: %.1f°C"
              args: [ 'id(t_h_jim_study_temperature).state' ]
        - lvgl.bar.update:
            id: bar_jim_study_temp
            value: !lambda 'return (id(t_h_jim_study_temperature).state) * $temp_bar_scale;'
  - platform: mqtt_subscribe
    id: t_h_sue_study_temperature
    topic: homeassistant/sensor/t_h_sue_study_temperature/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_sue_study_temp
            text:
              format: "Sue Study: %.1f°C"
              args: [ 'id(t_h_sue_study_temperature).state' ]
        - lvgl.bar.update:
            id: bar_sue_study_temp
            value: !lambda 'return (id(t_h_sue_study_temperature).state) * $temp_bar_scale;'
  - platform: mqtt_subscribe
    id: t_h_kitchen_temperature
    topic: homeassistant/sensor/t_h_kitchen_temperature/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_kitchen_temp
            text:
              format: "Kitchen: %.1f°C"
              args: [ 'id(t_h_kitchen_temperature).state' ]
        - lvgl.bar.update:
            id: bar_kitchen_temp
            value: !lambda 'return (id(t_h_kitchen_temperature).state) * $temp_bar_scale;'
  - platform: mqtt_subscribe
    id: t_h_lounge_temperature
    topic: homeassistant/sensor/t_h_lounge_temperature/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_lounge_temp
            text:
              format: "Lounge: %.1f°C"
              args: [ 'id(t_h_lounge_temperature).state' ]
        - lvgl.bar.update:
            id: bar_lounge_temp
            value: !lambda 'return (id(t_h_lounge_temperature).state) * $temp_bar_scale;'
  - platform: mqtt_subscribe
    id: t_h_hall_temperature
    topic: homeassistant/sensor/t_h_hall_temperature/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_hall_temp
            text:
              format: "Hall: %.1f°C"
              args: [ 'id(t_h_hall_temperature).state' ]
        - lvgl.bar.update:
            id: bar_hall_temp
            value: !lambda 'return (id(t_h_hall_temperature).state) * $temp_bar_scale;'
  - platform: mqtt_subscribe
    id: t_h_spare_room_temperature
    topic: homeassistant/sensor/t_h_spare_room_temperature/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_spare_rm_temp
            text:
              format: "Spare Rm: %.1f°C"
              args: [ 'id(t_h_spare_room_temperature).state' ]
        - lvgl.bar.update:
            id: bar_spare_rm_temp
            value: !lambda 'return (id(t_h_spare_room_temperature).state) * $temp_bar_scale;'
  - platform: mqtt_subscribe
    id: t_h_main_bed_rm_temperature
    topic: homeassistant/sensor/temperature_humidity_sensor_8_temperature/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_main_bed_rm_temp
            text:
              format: "Main BRm: %.1f°C"
              args: [ 'id(t_h_main_bed_rm_temperature).state' ]
        - lvgl.bar.update:
            id: bar_main_bed_rm_temp
            value: !lambda 'return (id(t_h_main_bed_rm_temperature).state) * $temp_bar_scale;'
  - platform: mqtt_subscribe
    id: t_h_jim_study_humidity
    topic: homeassistant/sensor/t_h_jim_study_humidity/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_jim_study_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_jim_study_humidity).state' ]  
        - lvgl.bar.update:
            id: bar_jim_study_humidity
            value: !lambda 'return id(t_h_jim_study_humidity).state;'
  - platform: mqtt_subscribe
    id: t_h_sue_study_humidity
    topic: homeassistant/sensor/t_h_sue_study_humidity/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_sue_study_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_sue_study_humidity).state' ]
        - lvgl.bar.update:  
            id: bar_sue_study_humidity
            value: !lambda 'return id(t_h_sue_study_humidity).state;'
  - platform: mqtt_subscribe
    id: t_h_kitchen_humidity
    topic: homeassistant/sensor/t_h_kitchen_humidity/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_kitchen_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_kitchen_humidity).state' ]
        - lvgl.bar.update:  
            id: bar_kitchen_humidity
            value: !lambda 'return id(t_h_kitchen_humidity).state;'
  - platform: mqtt_subscribe
    id: t_h_lounge_humidity
    topic: homeassistant/sensor/t_h_lounge_humidity/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_lounge_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_lounge_humidity).state' ]
        - lvgl.bar.update:
            id: bar_lounge_humidity
            value: !lambda 'return id(t_h_lounge_humidity).state;'
  - platform: mqtt_subscribe
    id: t_h_hall_humidity
    topic: homeassistant/sensor/t_h_hall_humidity/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_hall_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_hall_humidity).state' ]
        - lvgl.bar.update:
            id: bar_hall_humidity
            value: !lambda 'return id(t_h_hall_humidity).state;'
  - platform: mqtt_subscribe
    id: t_h_spare_room_humidity
    topic: homeassistant/sensor/t_h_spare_room_humidity/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_spare_rm_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_spare_room_humidity).state' ]
        - lvgl.bar.update:
            id: bar_spare_rm_humidity
            value: !lambda 'return id(t_h_spare_room_humidity).state;'
  - platform: mqtt_subscribe
    id: t_h_main_bed_rm_humidity
    topic: homeassistant/sensor/temperature_humidity_sensor_8_humidity/state
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_main_bed_rm_humidity
            text:
              format: "%.0f%%"
              args: [ 'id(t_h_main_bed_rm_humidity).state' ]
        - lvgl.bar.update:    
            id: bar_main_bed_rm_humidity
            value: !lambda 'return id(t_h_main_bed_rm_humidity).state;'

