#Specific setup to run code on a M5STack CoreS3 unit

esphome:
  name: ${esphome_name}
  friendly_name: ${friendly_name}
  on_boot:
    - priority: -100 #Ensure this runs after lvgl is initialised
      then:
        - delay: 4s
        - lvgl.widget.hide: boot_screen
        - delay: 20s # Give long enough for hardware to detect power state
        - script.execute: check_charger
        - script.execute: check_charge_level

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    ## Note: Disable these configurations if you face the boot loop issue.
    sdkconfig_options:
        CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
        CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
        CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
        # Moves instructions and read only data from flash into PSRAM on boot.
        # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
        # Considerably speeds up mWW at the cost of using more PSRAM.
        CONFIG_SPIRAM_RODATA: "y"
        CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: [axp2101, aw88298, aw9523b ]

i2c:
  - id: bus_internal
    sda: GPIO12
    scl: GPIO11

spi:
  - id: spi_bus
    clk_pin: GPIO36
    mosi_pin: GPIO37

axp2101:
  id: axp2101_pmu
  i2c_id: bus_internal

# IO Expander
aw9523b:
  - id: aw9523b_hub
    i2c_id: bus_internal

output:
  - platform: axp2101
    type: range
    channel: DLDO1
    id: lcd_backlight_output
    min_voltage: 2600
    max_voltage: 3300

  - platform: axp2101
    channel: ALDO1
    voltage: 1800

  - platform: axp2101
    channel: ALDO2
    voltage: 3300

  - platform: axp2101
    channel: BLDO1
    voltage: 2800

  - platform: axp2101
    channel: BLDO2
    voltage: 1500

touchscreen:
  - platform: ft63x6
    id: touch
    reset_pin:
      aw9523b: aw9523b_hub
      number: 0
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 240

display:
  - platform: mipi_spi
    model: M5CORE
    dc_pin: GPIO35
    reset_pin:
      aw9523b: aw9523b_hub
      number: 9
    cs_pin: 
      number: GPIO3
      ignore_strapping_warning: true
    data_rate: 40MHz
    invert_colors: true
    id: m5core_lcd
    # show_test_card: true

light:
  - platform: monochromatic
    id: display_backlight
    name: "LCD Backlight"
    icon: "mdi:television"
    entity_category: config
    output: lcd_backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

#=========================================================================================================


binary_sensor:

# some aw9523b inputs (handle interrupts)
# and other binary sensors
  # - platform: gpio
  #   name: "ES_INT P0_3"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 3
  #   on_press:
  #     then:
  #       - logger.log: "ES7210 interrupt triggered"
  #   internal: true

  # - platform: gpio
  #   name: "TF_SW P0_4"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 4 
  #   on_press:
  #     then:
  #       - logger.log: "TF_SW interrupt triggered"
  #   internal: true
  
  # - platform: gpio
  #   name: "TOUCH_INT P1_2"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 10
  #   on_press:
  #     then:
  #       - logger.log: "TOUCH interrupt triggered"
  #   internal: true

  # - platform: gpio
  #   name: "AW_INT P1_3"
  #   pin:
  #     aw9523b: aw9523b_hub
  #     number: 11
  #   on_press:
  #     then:
  #       - logger.log: "AW88298 interrupt triggered"
  #   internal: true

#=========================================================================================================
sensor:
# PMU
  - platform: axp2101
    id: axp2101_sensor
    # battery_voltage:
    #   name: "Battery Voltage"
    axp_temperature:
      name: "AXP2101 Temperature"
    battery_charging:
      id: charger_connected
      name: "Battery Charging"
      entity_category: "diagnostic"
      on_state: #When value changes update LVGL display
      - script.execute: check_charger
    battery_level:
      name: "Battery Level"
      id: battery_percent
      on_value:
        - script.execute: check_charge_level

lvgl:
  theme:
    label:
      text_font: montserrat_18 # set all your labels to use your custom defined font
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 2
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
#       focused:
# #        bg_color: 0x00cc00
#         border_color: 0xff0000
# #        bg_grad_dir: NONE
#         border_width: 4
    switch:
      bg_color: 0xC0C0C0
      bg_grad_color: 0xb0b0b0
      bg_grad_dir: VER
      bg_opa: COVER
      # focused:
      #   # bg_color: 0x00cc00
      #   border_color: 0xff0000
      #   # bg_grad_dir: NONE
      #   border_width: 2
      checked:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xFFFFFF
        bg_grad_color: 0xC0C0C0
        bg_grad_dir: VER
        bg_opa: COVER
    slider:
      border_width: 1
      border_opa: COVER
      bg_color: 0xcccaca
      bg_opa: COVER
      pad_all: 0
      pressed: #Occurs momentarily when changed value is accepted
        border_color: 0xff0000
        # bg_grad_dir: NONE
        border_width: 4
        border_opa: COVER
        bg_color: 0x00cc00 #only affects the background not covered by indicator bar
      # focused:
      #   border_color: 0xff0000
      #   # bg_grad_dir: NONE
      #   border_width: 2
      #   border_opa: COVER
      indicator:
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        bg_grad_dir: VER
        bg_opa: COVER
        focused:
          # bg_color: 0x00cc00
          border_color: 0xff0000
          # bg_grad_dir: NONE
          border_width: 2
      knob:
        bg_color: 0x2F8CD8
        bg_grad_color: 0x005782
        bg_grad_dir: VER
        bg_opa: COVER
        border_color: 0x0077b3
        border_width: 1
        text_color: 0xFFFFFF
        # focused:
        #   bg_color: 0x00cc00
        #   border_color: 0xff0000
        #   bg_grad_dir: NONE
        #   border_width: 2
#==========================================================================================================================
