esphome:
  name: ${esphome_name}

esp32:
  board: m5stack-core2
#  framework:
#    type: arduino
#     type: esp-idf
#  flash_size: 16MB # Need to manually override defaults so M5STACK FIRE memory is correct

psram: #Need to include this so logs will display PSRAM detected, note only 4MB detected even though 8MB exists (probably because himem not implemented)
  mode: quad
  speed: 80MHz

# Define I/O: UART, I²C and SPI
i2c:
  id: bus_a
  sda: 21
  scl: 22
  scan: true

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

# Power Management
# ip5306:
#   battery_level:
#     name: ${friendly_name} Battery Percent
#     id: battery_percent
#     on_value: #When value changes update LVGL display
#     - lvgl.label.update:
#         id: lbl_battery
#         text: !lambda |-
#           if (id(battery_percent).state == 100) {
#             return "\uF240";
#           } else if (id(battery_percent).state == 75) {
#             return "\uF241";
#           } else if (id(battery_percent).state == 50) {
#             return "\uF242";
#           } else if (id(battery_percent).state == 25) {
#             return "\uF243";
#           } else return "\uF244";
#   charger_connected:
#     name: ${friendly_name} Charger Connected
#     id: connected
#   charge_full:
#     name: ${friendly_name} Charge Full
#     id: full

external_components:
  - source:
      type: git
      url: https://github.com/suphammer/m5stack_core2_components.git
    refresh: 0s

axp192:
  id: axp
  address: 0x34
  i2c_id: bus_a
  update_interval: 60s

light:
  - platform: axp192
    id: backlight
    axp192_id: axp
    restore_mode: ALWAYS_ON
    name: "${devicename} Backlight"

# sensor:
#   - platform: axp192
#     axp192_id: axp
#     id: batterylevel
#     name: "${devicename} Battery Level"

# external_components:
# #  - source: github://martydingo/esphome-axp192
#   - source: github://suphammer/m5stack_core2_components
#     components: [axp192]

# sensor:
#   - platform: axp192
#     model: M5CORE2
#     address: 0x34
#     i2c_id: bus_a
#     id: axp192_id
#     update_interval: 30s
#     battery_level:
#       name: "${upper_devicename} Battery Level"
#       id: "${devicename}_batterylevel"

  # - platform: mpu6886
  #   address: 0x68
  #   update_interval: 1s
  #   accel_x:
  #     name: "MPU6886 Accel X"
  #   accel_y:
  #     name: "MPU6886 Accel Y"
  #   accel_z:
  #     name: "MPU6886 Accel Z"
  #   gyro_x:
  #     name: "MPU6886 Gyro X"
  #   gyro_y:
  #     name: "MPU6886 Gyro Y"
  #   gyro_z:
  #     name: "MPU6886 Gyro Z"
  #   temperature:
  #     name: "MPU6886 Temperature"

binary_sensor:
  - platform: axp192
    axp192_id: axp
    type: charging
    id: axp_charger
    name: "${devicename} Charger"
  # the virtual buttons--coordinates taken from
  # https://github.com/m5stack/M5Core2/blob/0134dd3a38cfd335a1ec39da2c149f88baf54326/src/M5Core2.h#L54-L56
  # and
  # https://github.com/m5stack/M5Core2/blob/0134dd3a38cfd335a1ec39da2c149f88baf54326/src/utility/M5Button.h#L811-L815
  # for the parameter order `(x, y, width, height)`
  - platform: touchscreen
    name: Button A
    id: M5_BtnA
    x_min: 10
    x_max: 120
    y_min: 240
    y_max: 280
#    use_raw: true
    # on_double_click:
    #   then: # Focus on top level buttons at bottom (of this page)
    #     - lvgl.widget.focus: top_layer

  - platform: touchscreen
    name: Button B
    id: M5_BtnB
    x_min: 130
    x_max: 200
    y_min: 240
    y_max: 280
#    use_raw: true
    # on_double_click:
    #   then: # Return to Home screen with focus on top level button for "next page" at bottom
    #     - lvgl.page.show: main_page
    #     - lvgl.widget.focus: page_next

  - platform: touchscreen
    name: Button C
    id: M5_BtnC
    x_min: 230
    x_max: 310
    y_min: 240
    y_max: 280
#    use_raw: true

# switch:
#   - platform: template
#     name: Antiburn
#     id: switch_antiburn
#     entity_category: "config"
#     icon: mdi:television-shimmer
#     optimistic: true
#     turn_on_action:
#       - logger.log: "Starting Antiburn"
#       - lvgl.pause:
#           show_snow: true
#     turn_off_action:
#       - logger.log: "Stopping Antiburn"
#       - lvgl.pause:
#           show_snow: false
#       - lvgl.resume:
#       - lvgl.widget.redraw:

# light:
#   - platform: monochromatic
#     output: gpio_32_backlight_pwm
#     name: "${friendly_name} Display Backlight"
#     id: back_light
#     restore_mode: RESTORE_DEFAULT_ON
    # on_state:
    #   - lvgl.slider.update:
    #       id: dimmer_slider #lvgl item that will adjust to reflect global backlight change LVGL slider needs value 0-255
    #       value: !lambda 'return (int(id(back_light).remote_values.get_brightness() * 255));' 

  # - platform: esp32_rmt_led_strip
  #   rgb_order: GRB
  #   pin: 
  #     number: GPIO15
  #     ignore_strapping_warning: true #This is correct pin for M5STACK FIRE Internal LED strips
  #   num_leds: 10
  #   rmt_channel: 1
  #   chipset: SK6812
  #   name: "${friendly_name} Side Light"
  #   restore_mode: RESTORE_AND_OFF # Attempt to restore state but initialize the light as OFF
  #   id: side_light
  #   default_transition_length: 0s
  #   effects:
  #     - addressable_rainbow:
  #     - addressable_color_wipe:
  #     - addressable_scan:
  #     - addressable_flicker:
  #     - addressable_fireworks:
  #     - addressable_random_twinkle:
  #     - addressable_twinkle:
  #     - pulse:
  #         name: "Alarm Pulse"
  #         transition_length: 0.5s
  #         update_interval: 0.5s
  #         min_brightness: 0%
  #         max_brightness: 100%
  #     - pulse:
  #         name: "Warn Pulse"
  #         transition_length: 1.5s
  #         update_interval: 2s
  #         min_brightness: 0%
  #         max_brightness: 50%


# output:
# # Internal LEDS
#   - platform: ledc # backlight output
#     pin: 32
#     id: gpio_32_backlight_pwm

display:
  - platform: ili9xxx
    id: m5stack_display #320x240 pixels
    model: ili9342
    cs_pin: GPIO5
    dc_pin: GPIO15
    invert_colors: true
    show_test_card: true
    auto_clear_enabled: false
    dimensions:
      width: 320
      height: 240
    transform:
      mirror_x: false # must be explicitly included, otherwise it defaults to true with the ili9342

touchscreen:
  - platform: ft63x6
    display: m5stack_display
    interrupt_pin: GPIO39
