esphome:
  name: ${esphome_name}

esp32:
  board: m5stack-fire
  framework:
    # type: arduino
    type: esp-idf
  flash_size: 16MB # Need to manually override defaults so M5STACK FIRE memory is correct

psram: #Need to include this so logs will display PSRAM detected, note only 4MB detected even though 8MB exists (probably because himem not implemented)
  mode: quad #JWS quad in latest esphome
  speed: 40MHz

external_components:
  - source: 
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ ip5306 ]

# Define I/O: UART, I²C and SPI
i2c:
  sda: 21
  scl: 22
  scan: true

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19
  interface: hardware
  # data_rate: 20MHz

# Power Management
ip5306:
  battery_level:
    name: Fire Battery
    id: battery_percent
    entity_category: "diagnostic"
    on_value: #When value changes update LVGL display
    - lvgl.label.update:
        id: lbl_battery
        text: !lambda |-
          if (id(battery_percent).state == 100) {
            return "\uF240";
          } else if (id(battery_percent).state == 75) {
            return "\uF241";
          } else if (id(battery_percent).state == 50) {
            return "\uF242";
          } else if (id(battery_percent).state == 25) {
            return "\uF243";
          } else return "\uF244";
  charger_connected:
    name: ${friendly_name} Charger Connected
    id: connected
    entity_category: "diagnostic"
  charge_full:
    name: ${friendly_name} Charge Full
    id: full
    entity_category: "diagnostic"

binary_sensor:
  - platform: gpio
    id: M5_BtnA
    pin:
      number: 39
      inverted: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_double_click:
      min_length: 50ms
      max_length: 200ms
      then: # Focus on top level buttons at bottom (of this page)
        - lvgl.widget.focus: 
            id: top_layer
  - platform: gpio
    id: M5_BtnB
    pin:
      number: 38
      inverted: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_double_click:
      min_length: 50ms
      max_length: 350ms
      then: # Return to Home screen with focus on top level button for "next page" at bottom
        - lvgl.page.show: main_page
        - lvgl.widget.focus: #Select the button matrix fram at bottom of screen
            id: top_layer
        - lvgl.matrix.button.update: #Select next page button
            id: page_next
            selected: true   
  - platform: gpio
    id: M5_BtnC
    pin:
      number: 37
      inverted: true
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms

switch:
  - platform: template
    name: Antiburn
    id: switch_antiburn
    entity_category: "config"
    icon: mdi:television-shimmer
    optimistic: true
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - lvgl.pause:
          show_snow: false
      - lvgl.resume:
      - lvgl.widget.redraw:

light:
  - platform: monochromatic
    output: gpio_32_backlight_pwm
    name: "${friendly_name} Display Backlight"
    id: display_backlight #back_light
    restore_mode: RESTORE_DEFAULT_ON
    # on_state:
    #   - lvgl.slider.update:
    #       id: dimmer_slider #lvgl item that will adjust to reflect global backlight change LVGL slider needs value 0-255
    #       value: !lambda 'return (int(id(back_light).remote_values.get_brightness() * 255));' 

  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 
      number: GPIO15
      ignore_strapping_warning: true #This is correct pin for M5STACK FIRE Internal LED strips
    num_leds: 10
    # rmt_channel: 1  #JWS ESPHome 2025.8.0 invalid
    chipset: SK6812
    name: "${friendly_name} Side Light"
    restore_mode: RESTORE_AND_OFF # Attempt to restore state but initialize the light as OFF
    id: side_light
    default_transition_length: 0s
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_flicker:
      - addressable_fireworks:
      - addressable_random_twinkle:
      - addressable_twinkle:
      - pulse:
          name: "Alarm Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Warn Pulse"
          transition_length: 1.5s
          update_interval: 2s
          min_brightness: 0%
          max_brightness: 50%


output:
# Internal LEDS
  - platform: ledc # backlight output
    pin: 32
    id: gpio_32_backlight_pwm

display:
  - platform: ili9xxx
    id: m5stack_display #320x240 pixels
    model: M5Stack
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    rotation: 0
    invert_colors: true
    auto_clear_enabled: false
    data_rate: 20MHz
