esphome:
  name: ${esphome_name}

mqtt:
  broker: allsmiths.synology.me
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  #no clientid reqd
  discovery: true # disable entity discovery
  discover_ip: true # enable device discovery
  discovery_retain: true #retain discovery messages
  discovery_unique_id_generator: mac #Use Mac address to generate unique entity Ids
#   on_connect:
#     - lvgl.widget.show: lbl_hastatus
#   on_disconnect:
#     - lvgl.widget.hide: lbl_hastatus

  on_message: 
    - topic: ${esphome_name}/restart
      then:
        - button.press: restart_button
    - topic: ${esphome_name}/ota
      then:
        - logger.log: "Starting OTA"
        - ota.http_request.flash:
            md5_url: https://github.com/jimwsmith/ESPHome/releases/download/${esphome_name}_ota/firmware.md5
            url: https://github.com/jimwsmith/ESPHome/releases/download/${esphome_name}_ota/firmware.ota.bin

text_sensor:
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_newsfeed
    topic: homeassistant/climate_newsfeed/state
    on_value: #When value changes update LVGL display
      - logger.log: "Climate newsfeed updated"
      - lvgl.label.update:
          id: lbl_scrolling_news
          text:
            format: " %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |"
            # args: [ id(climate_headline_0).state.c_str() ]
            # format: "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s "
            args: [ id(climate_headline_0).state.c_str() , id(climate_headline_1).state.c_str() , id(climate_headline_2).state.c_str() , id(climate_headline_3).state.c_str() , id(climate_headline_4).state.c_str() , id(climate_headline_5).state.c_str() , id(climate_headline_6).state.c_str() , id(climate_headline_7).state.c_str() , id(climate_headline_8).state.c_str() , id(climate_headline_9).state.c_str() ]
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_0
    topic: homeassistant/climate_newsfeed/headline_0
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_1
    topic: homeassistant/climate_newsfeed/headline_1
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_2
    topic: homeassistant/climate_newsfeed/headline_2
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_3
    topic: homeassistant/climate_newsfeed/headline_3
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_4
    topic: homeassistant/climate_newsfeed/headline_4
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_5
    topic: homeassistant/climate_newsfeed/headline_5
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_6
    topic: homeassistant/climate_newsfeed/headline_6
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_7
    topic: homeassistant/climate_newsfeed/headline_7
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_8
    topic: homeassistant/climate_newsfeed/headline_8
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: climate_headline_9
    topic: homeassistant/climate_newsfeed/headline_9

sensor: 
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm10_max
    topic: homeassistant/aqi_thresholds/pm10_max
    on_value:
      - lvgl.label.update:
          id: lbl_bar_pm10_max
          text:
            format: "%.0f" #Float but display only integer part
            args: [ 'x' ]
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm10_alarm
    topic: homeassistant/aqi_thresholds/pm10_alarm
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm10_warn
    topic: homeassistant/aqi_thresholds/pm10_warn

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm2_5_max
    topic: homeassistant/aqi_thresholds/pm2_5_max
    on_value:
      - script.execute: update_bar_pm2_5
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm2_5_alarm
    topic: homeassistant/aqi_thresholds/pm2_5_alarm
    on_value:
      - script.execute: update_bar_pm2_5
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: pm2_5_warn
    topic: homeassistant/aqi_thresholds/pm2_5_warn
    on_value:
      - script.execute: update_bar_pm2_5

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: no2_max
    topic: homeassistant/aqi_thresholds/no2_max
    on_value:
      - lvgl.label.update:
          id: lbl_bar_no2_max
          text:
            format: "%.0f" #Float but display only integer part
            args: [ 'x' ]
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: no2_alarm
    topic: homeassistant/aqi_thresholds/no2_alarm
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: no2_warn
    topic: homeassistant/aqi_thresholds/no2_warn

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co_max
    topic: homeassistant/aqi_thresholds/co_max
    on_value:
      - lvgl.label.update:
          id: lbl_bar_co_max
          text:
            format: "%.0f" #Float but display only integer part
            args: [ 'x' ]
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co_alarm
    topic: homeassistant/aqi_thresholds/co_alarm
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co_warn
    topic: homeassistant/aqi_thresholds/co_warn

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co2_max
    topic: homeassistant/aqi_thresholds/co2_max
    on_value:
      - lvgl.label.update:
          id: lbl_bar_co2_max
          text:
            format: "%.0f" #Float but display only integer part
            args: [ 'x' ]
      - lvgl.label.update:
          id: lbl_bar_co2b_max
          text:
            format: "%.0f" #Float but display only integer part
            args: [ 'x' ]
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co2_alarm
    topic: homeassistant/aqi_thresholds/co2_alarm
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: co2_warn
    topic: homeassistant/aqi_thresholds/co2_warn

  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: nh3_max
    topic: homeassistant/aqi_thresholds/nh3_max
    on_value:
      - lvgl.label.update:
          id: lbl_bar_nh3_max
          text:
            format: "%.0f" #Float but display only integer part
            args: [ 'x' ]
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: nh3_alarm
    topic: homeassistant/aqi_thresholds/nh3_alarm
  - platform: mqtt_subscribe
    internal: true # Mark this sensor as only for use within this code - we don't nee to feed it back out to Home Assistant since it came from there!
    id: nh3_warn
    topic: homeassistant/aqi_thresholds/nh3_warn


button: 
  - platform: restart
    id: restart_button
    name: Restart