esphome:
  name: ${esphome_name}

#Globals to remember counts of MQTT drops between reboots
globals:
  - id: mqtt_error_global
    type: int
    restore_value: yes
    initial_value: '0'

mqtt:
  id: mqtt_client #needed to be able to retrieve connection state in lambdas
  broker: allsmiths.synology.me
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  #no clientid reqd
  discovery: true # disable entity discovery
  discover_ip: true # enable device discovery
  discovery_retain: true #retain discovery messages
  discovery_unique_id_generator: mac #Use Mac address to generate unique entity Ids
  on_connect:
    then:
      - lvgl.led.update:
          id: led_mqtt
          color: GREEN
      - number.set:
          id: mqtt_error_count
          value: !lambda "return id(mqtt_error_global);"
  on_disconnect:
    then:
      - lvgl.led.update:
          id: led_mqtt
          color: RED
      - lambda: |-
          id(mqtt_error_global) += 1;
      - number.set:
          id: mqtt_error_count
          value: !lambda "return id(mqtt_error_global);"
  on_message: 
    - topic: ${esphome_name}/restart
      then:
        - button.press: restart_button
    - topic: ${esphome_name}/ota
      then:
        - logger.log: "Starting OTA"
        - ota.http_request.flash:
            md5_url: https://github.com/jimwsmith/ESPHome/releases/download/${esphome_name}_ota/firmware.md5
            url: https://github.com/jimwsmith/ESPHome/releases/download/${esphome_name}_ota/firmware.ota.bin

button: 
  - platform: restart
    id: restart_button
    name: Restart

number:
  - platform: template
    id: mqtt_error_count
    name: "MQTT Error Count"
    entity_category: "diagnostic"
    unit_of_measurement: "errors"
    max_value: 1000000
    min_value: 0  
    step: 1
    optimistic: true  
