# wifi.yaml file to be included as a package in esphome configurations
esphome:
  name: ${esphome_name}

http_request: 
  verify_ssl: false #ESP32 cannot manage SSL connections
  buffer_size_rx: 1024 #Needed to specify to allow ota to work, which it only does on esp-idf framework now.
  buffer_size_tx: 1024

ota:
  - platform: http_request # Triggered by a specific MQTT message
    on_begin:
        - lvgl.page.show: ota_page
        - lvgl.label.update:
            id: lbl_ota_source
            text: "MQTT Http OTA"
        - lambda: "id(lv_id).loop();" # Needed as main loop is blocked during OTA
    on_progress:
      then:
        - lvgl.bar.update:
            id: bar_ota_progress
            value: !lambda "return (int)x;"
        - lambda: "id(lv_id).loop();" # Needed as main loop is blocked during OTA
  - platform: esphome # Triggered by a normal software upload on same network
    password: !secret ota_password
    on_begin:
        - lvgl.page.show: ota_page
        - lvgl.label.update:
            id: lbl_ota_source
            text: "ESPHome OTA"
        - lambda: "id(lv_id).loop();" # Needed as main loop is blocked during OTA
    on_progress:
      then:
        - lvgl.bar.update:
            id: bar_ota_progress
            value: !lambda "return (int)x;"
        - lambda: "id(lv_id).loop();" # Needed as main loop is blocked during OTA

wifi:
#  output_power: 8.5  
  networks:
    - ssid: !secret wifi_comp_ssid
      password: !secret wifi_comp_password
    - ssid: !secret wifi_home_ssid
      password: !secret wifi_home_password
    - ssid: !secret wifi_phone_ssid
      password: !secret wifi_phone_password
    - ssid: !secret wifi_bshed_ssid
      password: !secret wifi_bshed_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "${friendly_name} Fallback Hotspot"
  #   password: "jJ1NYBE0mELq"
  on_connect:
    then:
      - lvgl.led.update:
          id: led_wifi
          color: GREEN
  on_disconnect:
    then:
      - lvgl.led.update:
          id: led_wifi
          color: RED
    # - lvgl.widget.hide: lbl_hastatus

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    icon: mdi:wifi
    name: "WiFi Signal dB"
    id: wifi_signal_db
    unit_of_measurement: "dB"
    update_interval: ${sensor_update}
    entity_category: "diagnostic"
    on_value:
        then:
          - lvgl.label.update:
              id: lbl_wifi_strength
              text:
                format: "Wi-Fi Strength: %.0fdB"
                args: [ 'id(wifi_signal_db).state' ]  
                
  - platform: uptime
    name: ${esphome_name} Uptime

text_sensor:
  - platform: wifi_info
    ssid:
      icon: mdi:wifi
      id: wifi_ssid
      name: WiFi SSID
      on_value:
          then:
            - lvgl.label.update:
                id: lbl_wifi_ssid
                text:
                  format: "Wi-Fi SSID: %s"
                  args: [ 'id(wifi_ssid).state.c_str()' ]  
                  # args: [ 'x' ]  
    dns_address:
      icon: mdi:wifi
      name: WiFi DNS Address
    ip_address:
      icon: mdi:wifi
      id: wifi_ip
      name: WiFi IP Address
      # update_interval: ${sensor_update} # stopped working in 2025.12.1
      entity_category: "diagnostic"
      on_value:
          then:
            - lvgl.label.update:
                id: lbl_wifi_ip
                text:
                  format: "Wi-Fi IP: %s"
                  args: [ 'id(wifi_ip).state.c_str()' ]  
                  # args: [ 'x' ]  
  #     address_0:
  #       name: ESP IP Address 0
  #     address_1:
  #       name: ESP IP Address 1
  #     address_2:
  #       name: ESP IP Address 2
  #     address_3:
  #       name: ESP IP Address 3
  #     address_4:
  #       name: ESP IP Address 4
  #   bssid:
  #     name: ESP Connected BSSID
  #   mac_address:
  #     name: ESP Mac Wifi Address
  #   scan_results:
  #     name: ESP Latest Scan Results
